// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1lBMqTMXfwiElXDtPs8cuChLJzrnOYCY',
    appId: '1:470936222817:web:1ad5ae741529e748c3be20',
    messagingSenderId: '470936222817',
    projectId: 'proyecto-fluterfire',
    authDomain: 'proyecto-fluterfire.firebaseapp.com',
    storageBucket: 'proyecto-fluterfire.appspot.com',
    measurementId: 'G-6TW1PHYMFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEjd3WhjBnUYfJhS8oT7xvXsDfKOBi9FU',
    appId: '1:470936222817:android:4c8ba098dc5fc1e8c3be20',
    messagingSenderId: '470936222817',
    projectId: 'proyecto-fluterfire',
    storageBucket: 'proyecto-fluterfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7yaUMr14KxhRDJu54a3iT-UOXrIHzF4',
    appId: '1:470936222817:ios:ec86c7b56b804096c3be20',
    messagingSenderId: '470936222817',
    projectId: 'proyecto-fluterfire',
    storageBucket: 'proyecto-fluterfire.appspot.com',
    iosClientId: '470936222817-8j9bs4jgcmoektjcfcqe36tmupriuv8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPrueba1000Tutoingles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7yaUMr14KxhRDJu54a3iT-UOXrIHzF4',
    appId: '1:470936222817:ios:ec86c7b56b804096c3be20',
    messagingSenderId: '470936222817',
    projectId: 'proyecto-fluterfire',
    storageBucket: 'proyecto-fluterfire.appspot.com',
    iosClientId: '470936222817-8j9bs4jgcmoektjcfcqe36tmupriuv8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPrueba1000Tutoingles',
  );
}
